--- #YAML:1.0
name: Test-WWW-Mechanize-Catalyst
version: 0.35
author:
  - Leon Brocard, C<< <acme@astray.com> >>
abstract: Test::WWW::Mechanize for Catalyst
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
