# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-WWW-Mechanize-Catalyst
version:      0.37
version_from: lib/Test/WWW/Mechanize/Catalyst.pm
installdirs:  site
requires:
    Catalyst:                      5.00
    Test::More:                    0
    Test::WWW::Mechanize:          1.04

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
