--- #YAML:1.0
name: Test-WWW-Mechanize-Catalyst
version: 0.29
author:
  - Leon Brocard <acme@astray.com>.
abstract: Test::WWW::Mechanize for Catalyst
license: perl
requires:
  Catalyst: 0
  Test::More: 0
provides:
  Test::WWW::Mechanize::Catalyst:
    file: lib/Test/WWW/Mechanize/Catalyst.pm
    version: 0.29
  Test::WWW::Mechanize::Catalyst::Aux:
    file: lib/Test/WWW/Mechanize/Catalyst.pm
    version: 0.29
generated_by: Module::Build version 0.2605
