--- #YAML:1.0
name:                Test-WWW-Mechanize-Catalyst
version:             0.39
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Catalyst:                      5.00
    Test::More:                    0
    Test::WWW::Mechanize:          1.14
    WWW::Mechanize:                1.30
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Leon Brocard <acme@astray.com>
