---
abstract: 'Test::WWW::Mechanize for Catalyst'
author:
  - 'Ash Berlin C<< <ash@cpan.org> >> (current maintiner)'
build_requires:
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::Dummy: 0
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0.88
  Test::utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Mechanize-Catalyst
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.90
  LWP: 5.816
  Moose: 0.67
  Test::WWW::Mechanize: 1.14
  WWW::Mechanize: 1.54
  namespace::clean: 0.09
  perl: 5.8.4
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/catagits/Test-WWW-Mechanize-Catalyst.git
version: 0.58
