---
abstract: 'Test::WWW::Mechanize for Catalyst'
author:
  - 'Ash Berlin C<< <ash@cpan.org> >> (current maintiner)'
build_requires:
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::Dummy: 0
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.770'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Mechanize-Catalyst
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.00
  LWP: 5.816
  Moose: 0.67
  Test::WWW::Mechanize: 1.14
  WWW::Mechanize: 1.50
  namespace::clean: 0.09
resources:
  license: http://dev.perl.org/licenses/
version: 0.50_1
